baseURL = "http://www.mattlayman.com/"
languageCode = "en-us"
title = "Matt Layman"
theme = "casper-two"

[params]
    title = "Matt Layman"
    subtitle = "A software creator"
    description = "Matt Layman is a software engineer from Frederick, MD. He is an open source software maintainer and advocate for the Python programming language."
